### PR TITLE
adjust layout so all icons are visible for test

### PR DESCRIPTION
**Pull request by sebastiankonieczek**
As the view was larger than the screen, the test could not find some of the icons of the toggle category because they where not visible.
Adjusting the layout makes these icons visible and furthermore allows scrolling/swiping in the tests.

### CODE REVIEW

**Comment by Razeeman** [comment]
Thank you for suggestion but CoordinatorLayout is there for the purpose of hiding icon categories list an icon type toggle on icons scroll. I didn't check but I think switching it to other layout would break this behaviour and generally it is not a good idea to change production code just so the tests would work. Probably the tests itself need to be looked at, I didn't spend much time on them so they can be flaky.

**Comment by sebastiankonieczek** [comment]
> Thank you for suggestion but CoordinatorLayout is there for the purpose of hiding icon categories list an icon type toggle on icons scroll. I didn't check but I think switching it to other layout would break this behaviour and generally it is not a good idea to change production code just so the tests would work. Probably the tests itself need to be looked at, I didn't spend much time on them so they can be flaky.

Hi, thank you for the hint, I agree with you on that topic! So I will try to find a better solution that will not affect existing behaviour.

**Comment by Razeeman** [comment]
By the way, is there a problem with this particular test? I run tests mostly on 29 api and don't remember this test ever failing. And github action tests are broken for other reasons it seems.

**Comment by sebastiankonieczek** [comment]
> By the way, is there a problem with this particular test? I run tests mostly on 29 api and don't remember this test ever failing. And github action tests are broken for other reasons it seems.

I am testing on api level 30 and this error occurs to me almost every time as for the last icon category not all icons are visible when the respective category is selected. I will try api version 29 and see if the error still occurs.

I will as well fix the linter checks so the ci actons hopefully succeed.

**Comment by sebastiankonieczek** [comment]
I found out that this is a toggling test and the repeat rule makes it pass relatively often. I can hardly reproduce the failing test now although it was failing for me constantly beforehand.

**Comment by Razeeman** [comment]
Oh, makes sence, I didn't try api 30 as it's relatively new. Thank you for the help with the tests, they are really messy at the moment.

By the way, it is possible that your git commits email is different from the one on the github profile, making it so you are not visible as a contributor. Don't know if it is important to you.

**Pull request merged**
