### PR TITLE
Features/add proportional display

### PR DESCRIPTION
**Pull request by sebastiankonieczek**

### CODE REVIEW

**Comment by Razeeman** [comment]
Hello! Thank you for making this PR. Can you provide a little information about motivation behind this changes? Why is it necessary to show fractional hours information?

**Comment by sebastiankonieczek** [comment]
> Hello! Thank you for making this PR. Can you provide a little information about motivation behind this changes? Why is it necessary to show fractional hours information?

Hi there, first of all, awesome work you did here very nice and clean code base! Was really easy to orientate myself although I am not very experienced with kotlin and android! And nice app of course :)

The motivation behind this PR is that, often you need to enter the tracked time to other time tracking tools, especially when you use the app for tracking your working hours.

The time tracking tools from other companies sometimes require entering fractional hours instead of hours and minutes. So it is more easy to enter the tracked time when you don't need to calculate the fractional hours but have them visible in the app right away.

Hope that makes clear why I'd love to have it :)

**Comment by Razeeman** [comment]
Thank you for providing more information! I understand your motivation now. I have some doubts though.

This app is supposed to be a simple tool, because of that I'm very cautious about overcomplicating it with features and information, especially the main screens (main, records and statistics). Adding proportional time additionally to existing format looks like a duplicated information and I'm not sure if a lot of people would actually need it. May I suggest maybe showing proportional time instead of current h:m format and add a setting to switch between this formats for people that would want it? What do you think?

**Comment by sebastiankonieczek** [comment]
> Thank you for providing more information! I understand your motivation now. I have some doubts though.
> 
> This app is supposed to be a simple tool, because of that I'm very cautious about overcomplicating it with features and information, especially the main screens (main, records and statistics). Adding proportional time additionally to existing format looks like a duplicated information and I'm not sure if a lot of people would actually need it. May I suggest maybe showing proportional time instead of current h:m format and add a setting to switch between this formats for people that would want it? What do you think?

Well that sounds pretty reasonable! One could think about a toggle button, but I guess I will start with an option in the settings as you proposed.

I would place the setting below the military time format, what do you think about that?

**Comment by Razeeman** [comment]
> I would place the setting below the military time format, what do you think about that?

Yep, that would be perfect. Don't forget about translations) Google Translate would do.

**Comment by Razeeman** [comment]
Thank you again for the work.

**Pull request merged**
